### ISSUE TITLE
Improvement in Read me ! 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [seema1711/seema1711#3]
## Change 1:- 
![Screenshot 2021-05-05 203920](https://user-images.githubusercontent.com/76584243/117164178-00a59d80-ade2-11eb-9445-eeac52d592f9.png)
You can add Social Media badges that will give eye-catching look! 

## Change 2:- 
![Screenshot 2021-05-05 204102](https://user-images.githubusercontent.com/76584243/117164434-3e0a2b00-ade2-11eb-88f8-10a2227f6cae.png)
You can add links to your certificates! 

## I liked that you have described the work in a very neat and clean way and point to point!

**Comment by iseemasaharan** [comment]
Thank you for the feedback, I have made changes!

**Comment by rohan-kulkarni-25** [comment]
Great Let's Close this issue then 👍🏻
